services:
  csg-stat:
    image: ghcr.io/sdrpsps/csg-stat:latest
    container_name: csg-stat
    user: "1000:1001"
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
    environment:
      - APP_BASE_PATH=
      - BETTER_AUTH_SECRET=
      - BETTER_AUTH_URL=
    restart: unless-stopped
